using AutoMapper;
using Microsoft.Extensions.Logging;
using MicroS_Common.Handlers;
using webook.domain.typeDePieces.Domain;
using webook.domain.typeDePieces.Dto;
using webook.domain.typeDePieces.Queries;
using WeBook.Services.ChannelManager.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri Jul 17 2020 11:35:07 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeBook.Services.ChannelManager.Handlers
{
    /// <summary>
    /// Browse TypeDePiece Handler
    /// </summary>
    public partial class BrowseTypeDePieceHandler : BaseBrowseHandler<TypeDePiece,string, BrowseTypeDePieces, TypeDePieceDto, IBrowseTypeDePieceRepository>
    {
        public BrowseTypeDePieceHandler(IBrowseTypeDePieceRepository repository, IMapper mapper,ILogger<BrowseTypeDePieceHandler> logger): base(repository, mapper,logger){}
    }
}
