using Chronicle;
using MicroS_Common;
using MicroS_Common.Authentication;
using MicroS_Common.Controllers;
using MicroS_Common.Dispatchers;
using MicroS_Common.Messages;
using MicroS_Common.RabbitMq;
using MicroS_Common.Types;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using OpenTracing;
using System;
using System.Diagnostics.CodeAnalysis;
using System.Linq;
using System.Threading.Tasks;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri Jul 17 2020 11:35:07 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.api.Controllers
{
    public abstract partial class BaseController : DispatcherBaseController
    {
        protected BaseController(IBusPublisher busPublisher, ITracer tracer, IDispatcher dispatcher, IConfiguration configuration, IOptions<AppOptions> appOptions) : base(busPublisher, tracer, dispatcher, configuration, appOptions)
        {
        }
    }
}
