using MicroS_Common;
using MicroS_Common.Controllers;
using MicroS_Common.Dispatchers;
using MicroS_Common.Mvc;
using MicroS_Common.RabbitMq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using OpenTracing;
using System;
using System.Threading.Tasks;
using webook.api.Framework;
using webook.api.Services;
using webook.domain.typeDeProprietes.Messages.Commands;
using webook.domain.typeDeProprietes.Queries;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 16:56:25 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.api.Controllers
{
    /// <summary>
    /// TypeDePropriete Controller that represent tha main API layer
    /// on wich each request must be made
    /// </summary>
    public partial class TypeDeProprietesController : DispatcherBaseController
    {
        public TypeDeProprietesController(IBusPublisher busPublisher, ITracer tracer, IDispatcher dispatcher, IConfiguration configuration, IOptions<AppOptions> appOptions) : base(busPublisher, tracer, dispatcher, configuration, appOptions)
        {
        }
    }
}
