
#region using
using AutoMapper;
using MicroS_Common.Mongo;
using MicroS_Common.Repository;
using System;
using webook.domain.proprietes.Domain;
using webook.domain.proprietes.Dto;
using webook.domain.proprietes.Queries;
#endregion

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 17:12:03 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeBook.Services.ChannelManager.Repositories
{    

    #region interface
    /// <summary>
    /// Propriete Repository for intereaction with database
    /// </summary>
    public interface IBrowseProprieteRepository : IBrowseRepository<Propriete,Guid,BrowseProprietes,ProprieteDto>{}
    #endregion 

    #region Implementation
    /// <summary>
    /// Propriete Repository for intereaction with database
    /// </summary>
    [Repository(typeof(IBrowseProprieteRepository))]
    public partial class ProprieteRepository : BrowseRepository<Propriete,Guid,BrowseProprietes,ProprieteDto>,IBrowseProprieteRepository 
    {
        public ProprieteRepository(IMongoRepository<Propriete,Guid> repository, IMapper mapper) : base(repository,mapper){}
        
    }
    #endregion
}