
#region using
using AutoMapper;
using MicroS_Common.Mongo;
using MicroS_Common.Repository;
using webook.domain.typeDeProprietes.Domain;
using webook.domain.typeDeProprietes.Dto;
using webook.domain.typeDeProprietes.Queries;
#endregion

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 16:56:25 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeBook.Services.ChannelManager.Repositories
{    

    #region interface
    /// <summary>
    /// TypeDePropriete Repository for intereaction with database
    /// </summary>
    public interface IBrowseTypeDeProprieteRepository : IBrowseRepository<TypeDePropriete,BrowseTypeDeProprietes,TypeDeProprieteDto>{}
    #endregion 

    #region Implementation
    /// <summary>
    /// TypeDePropriete Repository for intereaction with database
    /// </summary>
    [Repository(typeof(IBrowseTypeDeProprieteRepository))]
    public partial class TypeDeProprieteRepository : BrowseRepository<TypeDePropriete,BrowseTypeDeProprietes,TypeDeProprieteDto>,IBrowseTypeDeProprieteRepository 
    {
        public TypeDeProprieteRepository(IMongoRepository<TypeDePropriete> repository, IMapper mapper) : base(repository,mapper){}
        
    }
    #endregion
}