
#region using
using AutoMapper;
using MicroS_Common.Mongo;
using MicroS_Common.Repository;
using webook.domain.typeDePieces.Domain;
using webook.domain.typeDePieces.Dto;
using webook.domain.typeDePieces.Queries;
#endregion

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri Jul 17 2020 11:35:07 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeBook.Services.ChannelManager.Repositories
{    

    #region interface
    /// <summary>
    /// TypeDePiece Repository for intereaction with database
    /// </summary>
    public interface IBrowseTypeDePieceRepository : IBrowseRepository<TypeDePiece,string,BrowseTypeDePieces,TypeDePieceDto>{}
    #endregion 

    #region Implementation
    /// <summary>
    /// TypeDePiece Repository for intereaction with database
    /// </summary>
    [Repository(typeof(IBrowseTypeDePieceRepository))]
    public partial class TypeDePieceRepository : BrowseRepository<TypeDePiece,string,BrowseTypeDePieces,TypeDePieceDto>,IBrowseTypeDePieceRepository 
    {
        public TypeDePieceRepository(IMongoRepository<TypeDePiece,string> repository, IMapper mapper) : base(repository,mapper){}
        
    }
    #endregion
}