using System;
using MicroS_Common.Domain;
using webook.domain.typeDePieces.Messages.Events;


using WeCommon;
using MongoDB.Bson.Serialization.Attributes;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri Jul 17 2020 11:35:07 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.typeDePieces.Messages.Commands
{

    [OnRejected(typeof(CreateTypeDePieceRejected))]
    public class CreateTypeDePiece : TypeDePieceBaseCommand
    {
        
        public override string Id { get; set; }
        
        
        
        public Property<string> Nom {get;}


        public CreateTypeDePiece(string id,Property<string> nom) : base()
        {
            
            Id = id;
            
            Nom =nom; 

           
        }
    }
}
