using System;
using MicroS_Common.Domain;
using webook.domain.typeDePieces.Messages.Events;


using WeCommon;
using MongoDB.Bson.Serialization.Attributes;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri Jul 17 2020 11:35:07 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.typeDePieces.Messages.Commands
{
    [OnRejected(typeof(UpdateTypeDePieceRejected))]
    public class UpdateTypeDePiece : CreateTypeDePiece
    {
        
        public UpdateTypeDePiece(string id,Property<string> nom) : base(id,nom)
        {
        }
    }
}
