using MongoDB.Bson.Serialization.Attributes;
using System;
using System.Collections.Generic;

using WeCommon;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 16:56:24 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.typeDeProprietes.Dto
{
    public partial class TypeDeProprieteDto
    {

        #region private variables

        #endregion

        #region public properties

        public Guid Id { get; set; }
        [BsonSerializer(typeof(DynamicSerializer<dynamic, string>))]
        public dynamic Nom { get; set; }

        #endregion


    }
}
