#region using
using System;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Options;
using MicroS_Common;
using MicroS_Common.Types;
using MicroS_Common.Controllers;
using MicroS_Common.Dispatchers;
using webook.domain.typeDeProprietes.Dto;
using webook.domain.typeDeProprietes.Queries;
#endregion

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 16:56:25 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeBook.Services.ChannelManager.Controllers
{
    [Route("typeDeProprietes")]
    public partial class TypeDeProprietesController : BaseController
    {
        public TypeDeProprietesController(IDispatcher dispatcher,IConfiguration config,IOptions<AppOptions> appOptions) : base(dispatcher,config,appOptions)
        {
        }

        [HttpGet("")]
        public async Task<ActionResult<PagedResult<TypeDeProprieteDto>>> Get([FromQuery] BrowseTypeDeProprietes query)
            => Collection(await QueryAsync(query));

        [HttpGet("{id}")]
        public async Task<ActionResult<TypeDeProprieteDto>> Get([FromRoute] GetTypeDePropriete query)
            => Single(await QueryAsync(query));
        
        
    }
}