using MicroS_Common.Types;

using WeCommon;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri Jul 17 2020 11:35:07 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.typeDePieces.Dto
{
    public partial class TypeDePieceDto:EntityDto<string>
    {

        #region private variables
        
        #endregion

        #region public properties
        
         //public Guid Id { get; set; }
   
        
        public Property< string> Nom  {get;set;}
        
        #endregion


    }
}
