using System;
using MicroS_Common.Domain;
using webook.domain.proprietes.Messages.Events;


using WeCommon;
using MongoDB.Bson.Serialization.Attributes;
using webook.domain.proprietes.Domain;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 17:12:03 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.proprietes.Messages.Commands
{

    [OnRejected(typeof(CreateProprieteRejected))]
    public class CreatePropriete : ProprieteBaseCommand
    {

        public override Guid Id { get; set; }

        public string Nom { get; }
        public string Telephone { get; }
        public string Fax { get; }
        public string Email { get; }
        public string SiteWeb { get; }
        public string NomDuContact { get; }
        public string PrenomDuContact { get; }
        public string Devise { get; }
        public string SymboleDeDeviseAvantLePrix { get; }
        public string SymboleDeDeviseApresLePrix { get; }
        public string TypeDeLocation { get; }
        public string IdentifiantAutorite { get; }
        public int OrdreAffichage { get; }

        public Property<string> PolitiqueGenerale { get; }
        public Property<string> PolitiqueAnnulation { get; }
        public Adresse  Adresse{ get; set; }


        public CreatePropriete(
            Guid id, string nom, string telephone, string fax, string email, string siteweb, string nomducontact, string prenomducontact, string devise, string symbolededeviseavantleprix, string symbolededeviseapresleprix, string typedelocation, string identifiantautorite, int ordreaffichage, Property<string> politiquegenerale, Property<string> politiqueannulation,Adresse adresse) : base()
        {

            Id = id;

            Nom = nom;
            Telephone = telephone;
            Fax = fax;
            Email = email;
            SiteWeb = siteweb;
            NomDuContact = nomducontact;
            PrenomDuContact = prenomducontact;
            Devise = devise;
            SymboleDeDeviseAvantLePrix = symbolededeviseavantleprix;
            SymboleDeDeviseApresLePrix = symbolededeviseapresleprix;
            TypeDeLocation = typedelocation;
            IdentifiantAutorite = identifiantautorite;
            OrdreAffichage = ordreaffichage;
            PolitiqueGenerale = politiquegenerale;
            PolitiqueAnnulation = politiqueannulation;
            Adresse = adresse;

        }
    }
}
