using System;
using MicroS_Common.Messages;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 17:12:03 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.proprietes.Messages.Commands
{
    [MessageNamespace("proprietes")]
    public abstract class ProprieteBaseCommand : BaseCommand
    {

        public ProprieteBaseCommand() : base()
        {
        }
    }
}
