using AutoMapper;
using webook.domain.typeDeProprietes.Domain;
using webook.domain.typeDeProprietes.Dto;

using webook.domain.typeDeProprietes.Messages.Commands;
using webook.domain.typeDeProprietes.Messages.Events;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 16:56:24 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.typeDeProprietes.Mapping
{
    public class TypeDeProprieteProfile:Profile
    {
        public TypeDeProprieteProfile()
        {
            CreateMap<TypeDePropriete, TypeDeProprieteDto>();
            
            CreateMap<CreateTypeDePropriete, TypeDePropriete>();
            CreateMap<CreateTypeDePropriete, TypeDeProprieteCreated>();
            CreateMap<UpdateTypeDePropriete, TypeDeProprieteUpdated>();
            CreateMap<DeleteTypeDePropriete, TypeDeProprieteDeleted>();
            
        }
    }
}
