using AutoMapper;
using MicroS_Common.Handlers;
using MicroS_Common.Mongo;
using System.Threading.Tasks;
using webook.domain.typeDeProprietes.Dto;
using webook.domain.typeDeProprietes.Queries;
using WeBook.Services.ChannelManager.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 16:56:25 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeBook.Services.ChannelManager.Handlers
{
    /// <summary>
    /// Get TypeDePropriete Handler
    /// </summary>
    public partial class GetTypeDeProprieteHandler :  IQueryHandler<GetTypeDePropriete, TypeDeProprieteDto>
    {
        

        #region Constructors
        public GetTypeDeProprieteHandler(
            IBrowseTypeDeProprieteRepository repository,
             IMapper mapper)
        {
            Repository = repository;
            Mapper = mapper;
        }
        #endregion

        #region public properties
        public IBrowseTypeDeProprieteRepository Repository{get;}
        public IMapper Mapper{get;}
        #endregion

        #region public functions
        /// <summary>
        ///  Handle the command with context
        /// </summary>
        /// <param name="command">The command to handle</param>
        /// <param name="context">The correlation context</param>
        /// <returns></returns>
        public async Task<TypeDeProprieteDto> HandleAsync(GetTypeDePropriete query)
        {
            var model = await Repository.GetAsync(query.Id);

            return model == null ? null : Mapper.Map<TypeDeProprieteDto>(model);

        }
        #endregion
    }
}