using AutoMapper;
using MicroS_Common.Handlers;
using MicroS_Common.RabbitMq;
using MicroS_Common.Repository;
using MicroS_Common.Types;
using System;
using System.Threading.Tasks;
using webook.domain.typeDeProprietes.Domain;
using webook.domain.typeDeProprietes.Messages.Commands;
using webook.domain.typeDeProprietes.Messages.Events;
using WeBook.Services.ChannelManager.Repositories;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 16:56:25 GMT+0200 (GMT+02:00)
/// </summary>
namespace WeBook.Services.ChannelManager.Handlers
{
    /// <summary>
    /// Update TypeDePropriete Handler
    /// </summary>
    public partial class UpdateTypeDeProprieteHandler : DomainCommandHandler<UpdateTypeDePropriete, TypeDePropriete>
    {
        #region Constructors
        public UpdateTypeDeProprieteHandler(
            IBusPublisher busPublisher, 
            IMapper mapper, 
            IBrowseTypeDeProprieteRepository repo) : base(busPublisher, mapper, repo)
        {
        }
        #endregion
        #region Protected Overrides functions
        /// <summary>
        /// Check if the model exist by Command
        /// </summary>
        /// <param name="command">The command in wich information can be use do check if the model exist in database</param>
        /// <returns>Nothing</returns>
        protected override async Task<bool> CheckExist(Guid id)
        {
            if (!await base.CheckExist(id))
            {
                throw new MicroSException("typeDePropriete_not_found",$"TypeDePropriete with id: '{id}' was not found.");
            }
            return true;
        }
        #endregion
        #region Public Overrides functions
        /// <summary>
        ///  Handle the command with context
        /// </summary>
        /// <param name="command">The command to handle</param>
        /// <param name="context">The correlation context</param>
        /// <returns></returns>
        public override async Task HandleAsync(UpdateTypeDePropriete command, ICorrelationContext context)
        {
            
            await base.HandleAsync(command, context);
            var product = GetDomainObject(command);
            await Repository.UpdateAsync(product);
            await BusPublisher.PublishAsync(CreateEvent<TypeDeProprieteUpdated>(command), context);
        }
        #endregion
    }
}
