using System;
using System.Collections.Generic;

using WeCommon;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 16:56:24 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.typeDeProprietes.Messages.Events
{
    public class TypeDeProprieteCreated : TypeDeProprieteBaseEvent
    {
        public Guid Id { get; }

        
        public Property<string>  Nom{get;}
        
        
        #region Constructor
        public TypeDeProprieteCreated(Guid id,
        Property<string> nom
        )
        {
            Id = id;
            Nom = nom ;
            
            
        }
        #endregion
    }
}
