using Newtonsoft.Json;
using System;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 16:56:25 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.typeDeProprietes.Messages.Events
{
    public class TypeDeProprieteDeleted:TypeDeProprieteBaseEvent
    {

        public Guid Id { get; }

        public TypeDeProprieteDeleted(Guid id)
        {
            Id = id;
        }
    }
}
