using System;
using MicroS_Common.Mongo;


using WeCommon;
using MongoDB.Bson.Serialization.Attributes;
using MicroS_Common.Types;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri Jul 17 2020 11:35:07 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.typeDePieces.Domain
{
    [MongoDocument(COLLECTION_NAME)]
    public partial class TypeDePiece : Entity<string>,INom
    {
        public const string COLLECTION_NAME = "typeDePiece";
        #region private variables


        #endregion


        #region public properties


        [BsonSerializer(typeof(DynamicSerializer<dynamic, string>))]
        public dynamic Nom { get; set; } = new Property<string>();

        #endregion

        #region Constructeur
        public TypeDePiece() : base() { }

        public TypeDePiece(Property<string> nom)
            : base()
        {
            Nom = nom;
        }

        #endregion
        #region public functions
        #endregion

    }
}
