using AutoMapper;
using webook.domain.typeDePieces.Domain;
using webook.domain.typeDePieces.Dto;

using webook.domain.typeDePieces.Messages.Commands;
using webook.domain.typeDePieces.Messages.Events;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Fri Jul 17 2020 11:35:07 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.typeDePieces.Mapping
{
    public class TypeDePieceProfile:Profile
    {
        public TypeDePieceProfile()
        {
            CreateMap<TypeDePiece, TypeDePieceDto>();
            
            CreateMap<CreateTypeDePiece, TypeDePiece>();
            CreateMap<CreateTypeDePiece, TypeDePieceCreated>();
            CreateMap<UpdateTypeDePiece, TypeDePieceUpdated>();
            CreateMap<DeleteTypeDePiece, TypeDePieceDeleted>();
            
        }
    }
}
