using MicroS_Common.Types;
using MicroS_Common.RestEase;
using RestEase;
using System;
using System.Threading.Tasks;
using webook.domain.proprietes.Dto;
using webook.domain.proprietes.Queries;
using static webook.api.Services.ServiceForwarder;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 17:12:03 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.api.Services
{
    /// <summary>
    /// Propriete Service created by <see cref="https://www.nuget.org/packages/RestEase/">Restease</see>
    /// </summary>
    [ServiceForwarder(CHANNEL_MANAGER_SERVICE)]
    [SerializationMethods(Query = QuerySerializationMethod.Serialized)]
    public partial interface IProprietesService
    {
        /// <summary>
        /// Get propriete by its Id
        /// </summary>
        /// <param name="id">the id of  Propriete</param>
        /// <returns>ProprieteDto</returns>
        [AllowAnyStatusCode]
        [Get("proprietes/{id}")]
        Task<ProprieteDto> GetAsync([Path] Guid id);


         /// <summary>
        /// Get list of proprietes by BrowseProprietes Query
        /// </summary>
        /// <param name="query">The Browse proprietes query</param>
        /// <returns>a list of ProprieteDto</returns>
        [AllowAnyStatusCode]
        [Get("proprietes")]
        Task<PagedResult<ProprieteDto>> BrowseAsync([Query] BrowseProprietes query);
    }
}
