using MicroS_Common.Messages;
using System;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 17:12:03 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.proprietes.Messages.Events
{
    [MessageNamespace("proprietes")]
    public class ProprieteBaseRejectedEvent : BaseRejectedEvent
    {
        public ProprieteBaseRejectedEvent(Guid id, string reason, string code) : base(id, reason, code)
        {
        }
    }
}
