using System;
using System.Collections.Generic;
using WeCommon;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 17:12:03 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.proprietes.Messages.Events
{
    public class ProprieteUpdated : ProprieteCreated
    {
        public ProprieteUpdated(Guid id,string nom,string telephone,string fax,string email,string siteweb,string nomducontact,string prenomducontact,string devise,string symbolededeviseavantleprix,string symbolededeviseapresleprix,string typedelocation,string identifiantautorite,int ordreaffichage,Property<string> politiquegenerale,Property<string> politiqueannulation) 
        : base(id,nom,telephone,fax,email,siteweb,nomducontact,prenomducontact,devise,symbolededeviseavantleprix,symbolededeviseapresleprix,typedelocation,identifiantautorite,ordreaffichage,politiquegenerale,politiqueannulation)
        {
        }
    }
}
