using MicroS_Common.Types;
using webook.domain.proprietes.Dto;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 17:12:03 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.proprietes.Queries
{
    public class BrowseProprietes : PagedQueryBase, IQuery<PagedResult<ProprieteDto>>
    {
    }
}
