using MicroS_Common.Types;
using System;
using webook.domain.proprietes.Dto;

/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 17:12:03 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.proprietes.Queries
{
    public class GetPropriete : IQuery<ProprieteDto>
    {
        #region public properties
        
            public Guid Id { get; set; }
        
        #endregion
        
    }
}
