using System;
using webook.domain.proprietes.Domain;
using WeCommon;
/// <summary>
/// This file was generated by the yeoman generator "generator-micros"
/// @author: Ambert Jean-Christophe
/// @email: jc.ambert@free.fr
/// @created_on: Sun Jul 12 2020 17:12:03 GMT+0200 (GMT+02:00)
/// </summary>
namespace webook.domain.proprietes.Dto
{
    public partial class ProprieteDto
    {

        #region private variables

        #endregion

        #region public properties

        public Guid Id { get; set; }


        public string Nom { get; set; }

        public string Telephone { get; set; }

        public string Fax { get; set; }

        public string Email { get; set; }

        public string SiteWeb { get; set; }

        public string NomDuContact { get; set; }

        public string PrenomDuContact { get; set; }

        public string Devise { get; set; }

        public string SymboleDeDeviseAvantLePrix { get; set; }

        public string SymboleDeDeviseApresLePrix { get; set; }

        public Guid TypeDeLocation { get; set; }

        public string IdentifiantAutorite { get; set; }

        public int OrdreAffichage { get; set; }



        public Property<string> PolitiqueGenerale { get; set; }

        public Property<string> PolitiqueAnnulation { get; set; }

        public Adresse Adresse { get; set; }

        #endregion


    }
}
